
language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.1
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - howardbm@live.se
otp_release:
  - 18.0
  - 19.3
  - 20.0
env:
  - MIX_ENV=test
before_script:
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix do local.hex --force
  - mix deps.get
  - mix compile
  - mix coveralls.travis
  - dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/riemannx/ebin
matrix:
  exclude:
  - otp_release: 20
    elixir: 1.3.4
