
language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.1
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - howardbm@live.se
otp_release:
  - 18.0
  - 19.3
  - 20.0
env:
  - MIX_ENV=test
script:
  - mix do local.hex --force
  - mix deps.get
  - mix compile
  - mix coveralls.travis
matrix:
  exclude:
  - otp_release: 20
  - elixir: 1.3.4
