
language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.1
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - howardbm@live.se
otp_release:
  - 18.1
  - 19.2
  - 20.0
env:
  - MIX_ENV=test
before_script:
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  - $(wget -q -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME) || unset PLT_LOCATION; return 0
script:
  - mix do local.hex --force
  - mix deps.get
  - mix compile
  - travis_retry mix coveralls.travis
  - mix dialyzer --halt-exit-status
matrix:
  exclude:
  - otp_release: 20
    elixir: 1.3.4
  - otp_release: 19.2
    elixir: 1.5.1
  include:
  - otp_release: 19.3
    elixir: 1.5.1
